options:
  namespace:
    type: string
    default: "default"
    description: |
      The namespace in which the deployments will be set-up.
  isolated:
    type: boolean
    default: False
    description: |
      When true, the pods will only be able to receive traffic from inside the same namespace.